[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = false
size = 14

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.9
title = "Terminal"
