env:
  TERM: xterm-256color

window:
  opacity: 0.9
  dynamic_title: true
  decorations_theme_variant: None
  title: Terminal

cursor:
  blink_interval: 750
  blink_timeout: 5
  unfocused_hollow: true
  style:
    shape: Underline
    blinking: On

font:
  builtin_box_drawing: false
  size: 14
