name: Sync File Changes
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [sync]
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
          submodules: recursive
      
      - name: Create dotfiles directory
        run: rsync -av --exclude='.github' --exclude='.gitmodules' ./.[^.]* dotfiles

      - name: Create dotfiles branch
        uses: JamesIves/github-pages-deploy-action@a1ea191d508feb8485aceba848389d49f80ca2dc # v4.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: dotfiles
          FOLDER: dotfiles
          REPOSITORY_NAME: michael-valdron/dotfiles
          CLEAN: true